### ISSUE TITLE
Fail to Add Adaptor

### ISSUE THREAD

**Issue by Ricardokevins** [xashely/KeBioSum#4]
Hi~, i notice the convenient to add adaptor, So i try the following code (  code extract from pico_adapter_ml.py)
however i encounter the follow Error.
i also go through the HuggingFace Transformer's Docs and didn't find this API
![image](https://user-images.githubusercontent.com/43642508/151642522-e36bfb86-29ab-4ea5-98e3-0c9bcfd67a54.png)
![image](https://user-images.githubusercontent.com/43642508/151642529-27b2ee4b-b015-4f80-8930-62201dd83844.png)

**Comment by Ricardokevins** [comment]
thank you for any suggestion to solve this problem.

**Comment by xashely** [comment]
Hi, it seems like you need to install the package: adapter-transformers==2.0.0.

**Comment by Ricardokevins** [comment]
> adapter-transformers==2.0.0

Thanks! It works
